version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      DB_HOST: localhost
      DB_USER: postgres
      DB_PASS: postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres
